run:
  tests: false
  skip-dirs:
    - vendor/

  skip-files:
    - "_easyjson.go"
    - ".pb.go"
    - ".svc.go"

  modules-download-mode: readonly

linters-settings:
  golint:
    min-confidence: 0.3
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 200
  lll:
    line-length: 150
  funlen:
    statements: 100
    lines: 160


output:
  format: tab