.PHONY:

# ==============================================================================
# Generate swagger documentation
swagger_user_api:
	echo "Starting swagger generating"
	swag init -g **/**/*.go