DROP TABLE IF EXISTS hotels CASCADE;
DROP TRIGGER IF EXISTS hotel_updated_at_trigger ON hotels;
DROP FUNCTION IF EXISTS hotel_updated;
DROP EXTENSION IF EXISTS citext CASCADE;
DROP EXTENSION IF EXISTS POSTGIS CASCADE;
DROP EXTENSION IF EXISTS pg_trgm CASCADE;
DROP EXTENSION IF EXISTS btree_gist CASCADE;
DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;